[en]
title = "Professional site"
weight = 1
LanguageName = "EN"
contentDir = "content/english"


[pt-br]
title = "Site profissional"
description = "Professor | Pesquisador | Entusiasta de Open Source\n@Universidade de Brasília"
contentDir = "content/portuguese" 
weight = 2
LanguageName = "PT-br"
