[en]
title = "Professional site"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[pt-br]
title = "Site profissional"
# description = "Site Profissional - bla bla bla"
description = "Professor | Pesquisador | Entusiasta de Open Source"
contentDir = "content/portuguese" 
weight = 2
LanguageName = "PT-br"
