  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[main]]
  name = "Software Engineering"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Academic"
  weight = 400
  identifier = "accomplishments"

  [[main]]
  name = "Research"
  weight = 510
  identifier = "research"
  url = "/research/"
  parent = "accomplishments"  

  [[main]]
  name = "Education"
  weight = 520
  identifier = "education"
  url = "/education/"
  parent = "accomplishments"

  [[main]]
  name = "Science Diffusion"
  weight = 530
  identifier = "diffusion"
  url = "/diffusion/"
  parent = "accomplishments"

  [[main]]
  name = "Mentoring"
  weight = 540
  identifier = "mentoring"
  url = "/mentoring/"
  parent = "accomplishments"


  # [[main]]
  # name = "Contact"
  # weight = 600
  # identifier = "contact"
  # url = "/contact/"

  [[main]]
  name = "About"
  weight = 600
  identifier = "about"
  url = "/about/"
