  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  # [[main]]
  # name = "Blog"
  # weight = 200
  # identifier = "blog"
  # url = "/blog/"

  # [[main]]
  # name = "Software Engineering"
  # weight = 300
  # identifier = "portfolio"
  # url = "/portfolio/"

  [[main]]
  name = "Academic"
  weight = 400
  identifier = "academic"

  [[main]]
  name = "Research"
  weight = 510
  identifier = "research"
  url = "/research/"
  parent = "academic"

  [[main]]
  name = "Education"
  weight = 520
  identifier = "education"
  url = "/education/"
  parent = "academic"

  # [[main]]
  # name = "Science Diffusion"
  # weight = 530
  # identifier = "diffusion"
  # url = "/diffusion/"
  # parent = "academic"

  [[main]]
  name = "Mentoring"
  weight = 540
  identifier = "mentoring"
  url = "/mentoring/"
  parent = "academic"

  [[main]]
  name = "Academic Career"
  weight = 550
  identifier = "career"
  url = "/career/"
  parent = "academic"

  [[main]]
  name = "About"
  weight = 600
  identifier = "about"
  url = "/about/"

